server:
  port: 9094

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
      #路由id可以随意
      - id: user-service-route
        #代理的服务地址
        #uri: http://127.0.0.1:9091
        uri: lb://user-service  #默认负载均衡
        #路由断言:可以匹配的映射路径
        predicates:
        #- Path=/user/**
        #- Path=/**   #添加前缀
        - Path=/*/user/**   #去除前缀,*表示任意
        filters:
        #- PrefixPath=/user   #添加前缀
        - StripPrefix=1       #去除前缀,1表示去掉一个前缀,2表示去除两个前缀...
        - MyParam=age         #配置的局部过滤器
      #默认过滤器对所有路由都生效
      default-filters:
      #以下是添加响应头
      - AddResponseHeader=name,suyc
      - AddResponseHeader=age,18
      globalcors:
        corsConfigurations:
          '[/**]':
            #allowedOrigins: * # 这种写法或者下面的都可以，*表示全部
            allowedOrigins:
            - "http://docs.spring.io"
            allowedMethods:
            - GET
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9093/eureka
  instance:
    prefer-ip-address: true


#hystrix一些参数配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #修改超时时间
#ribbon一些参数配置
ribbon:
  ConnectTimeout: 1000 # 连接超时时长
  ReadTimeout: 2000 # 数据通信超时时长
  MaxAutoRetries: 0 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 0 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试
