server:
  port: 9093

#应用名
spring:
  application:
    name: eureka-server

#eureka服务地址
eureka:
  client:
    service-url:
      #eureka 服务地址，如果是集群的话；需要指定其它集群eureka地址
      defaultZone: http://localhost:9093/eureka,http://localhost:9097/eureka,http://localhost:9098/eureka
    # 注册自己
    register-with-eureka: true
    #不拉取服务,eureka不向自己拉取服务
    fetch-registry: true
  server:
    eviction-interval-timer-in-ms: 60000 # 服务失效剔除时间间隔，默认60秒，每隔60秒检查哪些服务失效
    enable-self-preservation: false     # 关闭自我保护模式（默认是打开的），生产开，研发关
